### ISSUE TITLE
Failing to import pkg_resources on windows

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#102]
Couldn't load plugin 'svir' 
ImportError: No module named pkg_resources

Traceback (most recent call last):
  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 281, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Miguel/.qgis2/python/plugins\svir\__init__.py", line 36, in 
    __import__('pkg_resources').declare_namespace(__name__)
  File "C:/PROGRA~1/QGISLY~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named pkg_resources

**Comment by mbernasocchi** [comment]
it is due to a missing python dependecy see http://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
looking if we can change this
