### ISSUE TITLE
Debug mode breaks the plugin on windows

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#127]
It looks like some logging operations that are done while in DEBUG mode break the plugin on windows. The priority of this is minor, because in normal mode everything seems to be fine and we usually debug the tool in a linux environment.

**Comment by ptormene** [comment]
The issue looks very weird: on windows, while in developer mode, things
* work correctly if the qgis python console is open (then debug logging does what is expected)
* break otherwise (failing to synchronize the qgis project variables)

**Comment by ptormene** [comment]
To reproduce the error:
1. restart QGIS
2. start a new project from scratch
3. import socioeconomic variables from the OQ-Platform
```
Traceback (most recent call last):
  File "C:/Users/vbox-gem/.qgis2/python/plugins\svir\irmt.py", line 428, in 
    project_definition))
  File "C:/Users/vbox-gem/.qgis2/python/plugins\svir\irmt.py", line 511, in _data_download_successful
    write_layer_suppl_info_to_qgs(layer.id(), suppl_info)
  File "C:/Users/vbox-gem/.qgis2/python/plugins\svir\utilities\utils.py", line 692, in write_layer_suppl_info_to_qgs
    layer_id, QgsProject.instance().readEntry('irmt', layer_id))
IOError: [Errno 9] Bad file descriptor
```
NOTE: If the python console is open, or if experiments are done while the console is open and then it is closed, things seem to work properly.
