### ISSUE TITLE
Unable to restore default colors in the plugin's settings on Mac OS X

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#198]
On Mac OS X, while opening the settings dialog, the `color_from` can not be restored, because of the following error:
```python
Traceback (most recent call last):
  File "/Users/user/.qgis2/python/plugins/svir/irmt.py", line 1207, in show_settings
    SettingsDialog(self.iface, self).exec_()
  File "/Users/user/.qgis2/python/plugins/svir/dialogs/settings_dialog.py", line 70, in __init__
    self.restoreState()
  File "/Users/user/.qgis2/python/plugins/svir/dialogs/settings_dialog.py", line 111, in restoreState
    self.set_button_color(self.style_color_from, style['color_from'])
  File "/Users/user/.qgis2/python/plugins/svir/dialogs/settings_dialog.py", line 124, in set_button_color
    button.setStyleSheet("background-color: %s" % color.name())
AttributeError: 'unicode' object has no attribute 'name'
```

**Comment by ptormene** [comment]
It was due to a corrupted setting that was previously stored, that instead of a QColor object contained a unicode object that had nothing to do with it. A way to solve it would be to delete that corrupted setting. In order to avoid this corner case, I am adding a sanity check in e004b2d, that restores the default values of color_from and color_to in case the object retrieved from the settings is not a QColor.

**Comment by ptormene** [comment]
We should show a warning message in case a corrupted setting is found and it is replaced by the default.
