### ISSUE TITLE
Error importing matplotlib.pyplot on Windows 64bit

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#224]
The plugin can not be loaded on Windows 64 bit
The line that produces the error is:
```python
import matplotlib.pyplot as plt
```

Stacktrace produced by QGIS 2.18.7:
```python
ImportError: No module named Tkinter 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Paul Henshaw/.qgis2/python/plugins\svir\__init__.py", line 30, in classFactory
    from svir.irmt import Irmt
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Paul Henshaw/.qgis2/python/plugins\svir\irmt.py", line 59, in 
    from svir.dialogs.viewer_dock import ViewerDock
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Paul Henshaw/.qgis2/python/plugins\svir\dialogs\viewer_dock.py", line 50, in 
    from svir.recovery_modeling.recovery_modeling import (
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Paul Henshaw/.qgis2/python/plugins\svir\recovery_modeling\recovery_modeling.py", line 29, in 
    import matplotlib.pyplot as plt
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib\pyplot.py", line 115, in 
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib\backends\__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\matplotlib\backends\backend_tkagg.py", line 6, in 
    from six.moves import tkinter as Tk
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\six.py", line 203, in load_module
    mod = mod._resolve()
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\six.py", line 82, in _import_module
    __import__(name)
  File "C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named Tkinter
```

**Comment by ptormene** [comment]
If all occurrences of `import matplotlib.pyplot as plt are changed into:
```python
import matplotlib as mpl
mpl.use('Qt4Agg')  # or mpl.use('agg')
import matplotlib.pyplot as plt
```
then the following procedure does not produce any error:

1. uncheck the plugin in the plugins manager
2. restart QGIS (the plugin is not loaded yet)
3. check the plugin in the plugins manager (the plugin is loaded correctly)
4. run a full (batch) recovery modeling calculation (that plots curves as PNG files)

But... If you restart QGIS afterwards, it breaks.
This seems to suggest that only if the plugin is loaded after everything else, the environment variables are properly set.

**Comment by daniviga** [comment]
I confirm that QGIS 2.18.14 has still this issue with missing `Tkinter`

**Comment by ptormene** [comment]
We should improve the error message in case of failure when importing matplotlib

**Comment by ptormene** [comment]
Fixed in:
https://github.com/gem/oq-irmt-qgis/pull/467
https://github.com/gem/oq-irmt-qgis/pull/468
