### ISSUE TITLE
`dmg_by_asset` can't be loaded in case of multiple realizations

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#267]
The plugin is expecting to parse a single csv file instead of a zip file containing a csv for each realization. This works only in case of a single realization, otherwise it fails, and the traceback does not give any clear suggestion:
```python
Traceback (most recent call last):
  File "/home/paolo/.qgis2/python/plugins/svir/dialogs/drive_oq_engine_server_dialog.py", line 546, in 
    self.on_output_action_btn_clicked(output, action, outtype))
  File "/home/paolo/.qgis2/python/plugins/svir/dialogs/drive_oq_engine_server_dialog.py", line 582, in on_output_action_btn_clicked
    self.iface, self.viewer_dock, output_type, filepath)
  File "/home/paolo/.qgis2/python/plugins/svir/dialogs/load_dmg_by_asset_as_layer_dialog.py", line 49, in __init__
    self.read_loss_types_and_dmg_states_from_csv_header()
  File "/home/paolo/.qgis2/python/plugins/svir/dialogs/load_dmg_by_asset_as_layer_dialog.py", line 91, in read_loss_types_and_dmg_states_from_csv_header
    reader = csv.reader(source)
Error: line contains NULL byte
```

**Comment by ptormene** [comment]
I prefer to avoid implementing a more complex loader for csv outputs. I would rather switch to a new loader from npz as soon as it becomes available engine-side.

**Comment by ptormene** [comment]
Closed by https://github.com/gem/oq-irmt-qgis/pull/279
