### ISSUE TITLE
Error when uninstalling plugin from QGIS 3

### ISSUE THREAD

**Issue by daniviga** [gem/oq-irmt-qgis#464]
```
Error while unloading plugin svir 

RuntimeError: wrapped C/C++ object of type QMenu has been deleted 
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/qgis/utils.py", line 392, in unloadPlugin
    plugins[packageName].unload()
  File "/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/svir/irmt.py", line 527, in unload
RuntimeError: wrapped C/C++ object of type QMenu has been deleted


Python version: 3.6.5 (default, Mar 29 2018, 18:20:46) [GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)] 
QGIS version: 3.2.0-Bonn Bonn, exported 

Python Path:
/usr/share/qgis/python
/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python
/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib64/python36.zip
/usr/lib64/python3.6
/usr/lib64/python3.6/lib-dynload
/usr/lib64/python3.6/site-packages
/usr/lib/python3.6/site-packages
/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python
```

**Comment by daniviga** [comment]
It looks like gone

**Comment by daniviga** [comment]
No ok: it is not always reproducible:

- install plugin -> restart qgis -> uninstall plugin: WORKS
- install plugin -> uninstall plugin: ERROR
