### ISSUE TITLE
Plugin settings button triggers an error

### ISSUE THREAD

**Issue by daniviga** [gem/oq-irmt-qgis#633]
When clicking the 'gear' button i get this error:

```python
An error has occurred while executing Python code: 

OverflowError: argument 1 overflowed: value must be in the range 0 to 4294967295 
Traceback (most recent call last):
  File "/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/svir/irmt.py", line 1257, in show_settings
    SettingsDialog(self.iface, self).exec_()
  File "/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/svir/dialogs/settings_dialog.py", line 93, in __init__
    self.restore_state()
  File "/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/svir/dialogs/settings_dialog.py", line 130, in restore_state
    restore_defaults)
  File "/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python/plugins/svir/utilities/utils.py", line 877, in get_style
    color_from = QColor().fromRgba(color_from_rgba)
OverflowError: argument 1 overflowed: value must be in the range 0 to 4294967295


Python version: 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] 
QGIS version: 3.8.2-Zanzibar Zanzibar, exported 

Python Path:
/usr/share/qgis/python
/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python
/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib64/python37.zip
/usr/lib64/python3.7
/usr/lib64/python3.7/lib-dynload
/usr/lib64/python3.7/site-packages
/usr/lib/python3.7/site-packages
/home/daniele/.local/share/QGIS/QGIS3/profiles/default/python
.
```

Plugin version: 3.7.0

QGIS version | 3.8.2-Zanzibar | QGIS code branch | Release 3.8
-- | -- | -- | --
Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
Compiled against GDAL/OGR | 2.3.2 | Running against GDAL/OGR | 2.3.2
Compiled against GEOS | 3.7.1-CAPI-1.11.1 | Running against GEOS | 3.7.1-CAPI-1.11.1 27a5e771
PostgreSQL Client Version | 11.4 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Fedora 30 (Workstation Edition) |   |

**Comment by daniviga** [comment]
Cleaning up the `irmt` settings in the `QGIS3.ini` did not worked.

**Comment by daniviga** [comment]
Already fixed in master (via https://github.com/gem/oq-irmt-qgis/pull/627)
