### ISSUE TITLE
Earthquake Ruptures visualisation broken

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-irmt-qgis#673]
The load Earthquake Ruptures is broken for event_based and eb_risk calculations

`Unable to load layer 
Traceback (most recent call last):
  File "/Users/cyepes/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/svir/dialogs/load_ruptures_as_layer_dialog.py", line 110, in load_from_csv
    dest_shp=dest_shp)
  File "/Users/cyepes/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/svir/utilities/utils.py", line 1030, in import_layer_from_csv
    raise RuntimeError('Unable to load layer')
RuntimeError: Unable to load layer `

**Comment by ptormene** [comment]
Fixed by https://github.com/gem/oq-irmt-qgis/pull/684
