### ISSUE TITLE
Error on Win10 with OQ3.11 and IRMT3.11.2

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#772]
```python
Traceback (most recent call last):
  File "C:/Users/paulh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\svir\dialogs\drive_oq_engine_server_dialog.py", line 965, in 
    output, action, outtype, calculation_mode)))
  File "C:/Users/paulh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\svir\dialogs\drive_oq_engine_server_dialog.py", line 1002, in on_output_action_btn_clicked
    output_id, output_type, calculation_mode=calculation_mode)
  File "C:/Users/paulh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\svir\dialogs\drive_oq_engine_server_dialog.py", line 1072, in open_output
    calculation_mode=calculation_mode)
  File "C:/Users/paulh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\svir\dialogs\load_avg_losses_rlzs_as_layer_dialog.py", line 49, in __init__
    calculation_mode=calculation_mode)
  File "C:/Users/paulh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\svir\dialogs\load_output_as_layer_dialog.py", line 122, in __init__
    self.oqparam = self.drive_engine_dlg.get_oqparam()
  File "C:/Users/paulh/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\svir\dialogs\drive_oq_engine_server_dialog.py", line 821, in get_oqparam
    return json.loads(js)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 17 (char 18)
```

**Comment by ptormene** [comment]
The error turned out to be OQ-Engine side, and it was fixed in https://github.com/gem/oq-engine/pull/6632

**Comment by ptormene** [comment]
This is not a problem anymore
